import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <navi>
        <Link href="/getstarted">Get Started</Link>
        <Link href="/setting">Setting</Link>
      </navi>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
